// Generated by gencpp from file my_data_types/my_data_type.msg
// DO NOT EDIT!


#ifndef MY_DATA_TYPES_MESSAGE_MY_DATA_TYPE_H
#define MY_DATA_TYPES_MESSAGE_MY_DATA_TYPE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace my_data_types
{
template <class ContainerAllocator>
struct my_data_type_
{
  typedef my_data_type_<ContainerAllocator> Type;

  my_data_type_()
    : header()
    , id(0)
    , my_data()  {
    }
  my_data_type_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , id(0)
    , my_data(_alloc)  {
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _id_type;
  _id_type id;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _my_data_type;
  _my_data_type my_data;




  typedef boost::shared_ptr< ::my_data_types::my_data_type_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_data_types::my_data_type_<ContainerAllocator> const> ConstPtr;

}; // struct my_data_type_

typedef ::my_data_types::my_data_type_<std::allocator<void> > my_data_type;

typedef boost::shared_ptr< ::my_data_types::my_data_type > my_data_typePtr;
typedef boost::shared_ptr< ::my_data_types::my_data_type const> my_data_typeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_data_types::my_data_type_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_data_types::my_data_type_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace my_data_types

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'my_data_types': ['/home/intempora/rtmaps-ros-bridge/rtmaps_ros_custom_data_types/catkin_ws/src/my_data_types/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::my_data_types::my_data_type_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_data_types::my_data_type_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_data_types::my_data_type_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_data_types::my_data_type_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_data_types::my_data_type_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_data_types::my_data_type_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_data_types::my_data_type_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fb71f34f8ba59a227d3fb9a24273a811";
  }

  static const char* value(const ::my_data_types::my_data_type_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfb71f34f8ba59a22ULL;
  static const uint64_t static_value2 = 0x7d3fb9a24273a811ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_data_types::my_data_type_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_data_types/my_data_type";
  }

  static const char* value(const ::my_data_types::my_data_type_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_data_types::my_data_type_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
int32  id\n\
float32[] my_data\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::my_data_types::my_data_type_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_data_types::my_data_type_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.id);
      stream.next(m.my_data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct my_data_type_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_data_types::my_data_type_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_data_types::my_data_type_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    s << indent << "my_data[]" << std::endl;
    for (size_t i = 0; i < v.my_data.size(); ++i)
    {
      s << indent << "  my_data[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.my_data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_DATA_TYPES_MESSAGE_MY_DATA_TYPE_H
